version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    restart: unless-stopped
    depends_on:
        - db

  db:
    image: 'bitnami/mongodb:4.2.1'
    volumes:
      - 'mongodb_data:/bitnami'
    logging:
      driver: none

volumes:
  mongodb_data:
    driver: local
