version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped

  db:
    image: 'bitnami/mongodb:4.2.1'
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    logging:
      driver: none

volumes:
  mongodb_data:
    driver: local
